[package]
name = "adapters"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
domain.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
rust_decimal.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
parquet.workspace = true
arrow-schema.workspace = true
arrow-array.workspace = true
zip.workspace = true
reqwest.workspace = true
clap.workspace = true
indicatif.workspace = true
tempfile = "3"
tokio-tungstenite.workspace = true
futures-util.workspace = true
ring.workspace = true
chrono.workspace = true


[[bin]]
name = "fetch_data"
path = "src/bin/fetch_data.rs"

[[bin]]
name = "stream_trades"
path = "src/bin/stream_trades.rs"

[[bin]]
name = "live_gateway"
path = "src/bin/live_gateway.rs"


[dev-dependencies]
rust_decimal_macros.workspace = true
