//! Real-time paper trading engine for ATSNT.
//!
//! Provides live event-driven paper execution matching incoming trade ticks against
//! synthetic dollar bar aggregations, executing signals via the deterministic [`BacktestEngine`],
//! and broadcasting real-time lifecycle events ([`PaperTradingEvent`]) over Tokio channels.

use domain::{DollarBar, DollarBarAggregator, Position, PositionSide, Trade};
use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use serde::{Deserialize, Serialize};
use strategies::{DollarBarsCusumConfig, DollarBarsCusumStrategy};
use tokio::sync::broadcast;

use crate::config::BacktestConfig;
use crate::engine::BacktestEngine;
use crate::error::BacktestError;
use crate::metrics::{BacktestMetrics, ClosedTrade};

/// Real-time lifecycle events emitted during paper trading execution.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PaperTradingEvent {
    /// A new Dollar Bar has finalized after reaching the sampling dollar threshold.
    BarFormed(DollarBar),
    /// An algorithmic trading signal intent was generated by the active strategy.
    SignalGenerated(domain::OrderIntent),
    /// A simulated market position has opened with friction (slippage + fee drag).
    PositionOpened {
        /// Position side (Long or Short).
        side: PositionSide,
        /// Simulated execution entry price (including slippage).
        entry_price: Decimal,
        /// Executed order size in base asset units.
        quantity: Decimal,
        /// Stop loss barrier price.
        stop_loss: Decimal,
        /// Take profit barrier price.
        take_profit: Decimal,
    },
    /// A simulated market position has closed due to barrier breach or time limit.
    PositionClosed {
        /// Reason for exit: "StopLoss", "TakeProfit", or "TimeBarrier".
        exit_reason: String,
        /// Simulated exit execution price.
        exit_price: Decimal,
        /// Realized net PnL after all fees and slippage.
        net_pnl: Decimal,
        /// Updated portfolio cash equity after trade settlement.
        total_equity: Decimal,
    },
    /// Live mark-to-market valuation against incoming market trade tick.
    MarkToMarket {
        /// Current market price tick.
        current_price: Decimal,
        /// Current unrealized PnL of active position.
        unrealized_pnl: Decimal,
        /// Total portfolio equity including unrealized PnL.
        total_equity: Decimal,
        /// Current peak-to-trough drawdown percentage.
        drawdown_pct: Decimal,
    },
}

/// Configuration settings for initializing a [`PaperTradingSession`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PaperTradingConfig {
    /// Information threshold in quote currency (USDT) to aggregate a Dollar Bar.
    pub dollar_bar_threshold: Decimal,
    /// Backtesting friction and account parameters.
    pub backtest: BacktestConfig,
    /// Strategy hyperparameters.
    pub strategy: DollarBarsCusumConfig,
    /// Capacity of the Tokio broadcast event channel. Default: 10,000.
    pub channel_capacity: usize,
}

impl Default for PaperTradingConfig {
    fn default() -> Self {
        Self {
            dollar_bar_threshold: dec!(50_000),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig::default(),
            channel_capacity: 10_000,
        }
    }
}

/// Live event-driven paper trading session coordinator.
///
/// Bridges live incoming market trades with the deterministic [`BacktestEngine`]
/// and [`DollarBarsCusumStrategy`], broadcasting execution telemetry in real time.
pub struct PaperTradingSession {
    aggregator: DollarBarAggregator,
    strategy: DollarBarsCusumStrategy,
    engine: BacktestEngine,
    event_sender: broadcast::Sender<PaperTradingEvent>,
}

impl PaperTradingSession {
    /// Initializes a new paper trading session from the provided configuration.
    pub fn new(config: PaperTradingConfig) -> Result<Self, BacktestError> {
        let aggregator = DollarBarAggregator::new(config.dollar_bar_threshold)?;
        let strategy = DollarBarsCusumStrategy::new(config.strategy)?;
        let engine = BacktestEngine::new(config.backtest);
        let capacity = if config.channel_capacity == 0 {
            10_000
        } else {
            config.channel_capacity
        };
        let (event_sender, _) = broadcast::channel(capacity);

        Ok(Self {
            aggregator,
            strategy,
            engine,
            event_sender,
        })
    }

    /// Initializes a paper trading session with pre-built components.
    pub fn from_components(
        aggregator: DollarBarAggregator,
        strategy: DollarBarsCusumStrategy,
        engine: BacktestEngine,
        channel_capacity: usize,
    ) -> Self {
        let capacity = if channel_capacity == 0 {
            10_000
        } else {
            channel_capacity
        };
        let (event_sender, _) = broadcast::channel(capacity);

        Self {
            aggregator,
            strategy,
            engine,
            event_sender,
        }
    }

    /// Creates a new broadcast receiver to subscribe to live paper trading events.
    pub fn subscribe(&self) -> broadcast::Receiver<PaperTradingEvent> {
        self.event_sender.subscribe()
    }

    /// Access the underlying broadcast sender channel.
    pub fn event_sender(&self) -> broadcast::Sender<PaperTradingEvent> {
        self.event_sender.clone()
    }

    /// Ingests a live market trade, steps the aggregator, evaluates strategy signals
    /// and barrier exits, and returns all events generated during this tick.
    pub fn process_trade(&mut self, trade: &Trade) -> Vec<PaperTradingEvent> {
        let mut events = Vec::new();

        // 1. Mark to market on current trade if there is an active position
        if let Some(pos) = self.engine.active_position() {
            let unrealized_pnl = pos.unrealized_pnl(trade.price);
            let total_equity = self.engine.total_equity(trade.price);
            let peak_equity = self.engine.peak_equity();
            let drawdown_pct = if peak_equity > Decimal::ZERO && peak_equity > total_equity {
                (peak_equity - total_equity) / peak_equity
            } else {
                Decimal::ZERO
            };

            events.push(PaperTradingEvent::MarkToMarket {
                current_price: trade.price,
                unrealized_pnl,
                total_equity,
                drawdown_pct,
            });
        }

        // 2. Ingest trade into the DollarBarAggregator
        if let Some(bar) = self.aggregator.process_trade(trade) {
            events.push(PaperTradingEvent::BarFormed(bar.clone()));

            let had_pos = self.engine.active_position().cloned();
            let had_intent = self.engine.active_intent().cloned();
            let next_bars_held = self.engine.bars_held() + 1;

            self.engine.process_bar(&mut self.strategy, &bar);

            // Check if active position closed
            if let (Some(pos), Some(intent)) = (had_pos, had_intent) {
                if self.engine.active_position().is_none() {
                    let exit_reason = match pos.side {
                        PositionSide::Long => {
                            if bar.low <= intent.stop_loss {
                                "StopLoss"
                            } else if bar.high >= intent.take_profit {
                                "TakeProfit"
                            } else if next_bars_held >= intent.max_bars_hold {
                                "TimeBarrier"
                            } else {
                                "Unknown"
                            }
                        }
                        PositionSide::Short => {
                            if bar.high >= intent.stop_loss {
                                "StopLoss"
                            } else if bar.low <= intent.take_profit {
                                "TakeProfit"
                            } else if next_bars_held >= intent.max_bars_hold {
                                "TimeBarrier"
                            } else {
                                "Unknown"
                            }
                        }
                    };

                    if let Some(closed_trade) = self.engine.closed_trades().last() {
                        let exit_price = if pos.quantity > Decimal::ZERO {
                            match pos.side {
                                PositionSide::Long => {
                                    pos.entry_price + (closed_trade.pnl_gross / pos.quantity)
                                }
                                PositionSide::Short => {
                                    pos.entry_price - (closed_trade.pnl_gross / pos.quantity)
                                }
                            }
                        } else {
                            bar.close
                        };

                        events.push(PaperTradingEvent::PositionClosed {
                            exit_reason: exit_reason.to_string(),
                            exit_price,
                            net_pnl: closed_trade.pnl_net,
                            total_equity: self.engine.cash_equity(),
                        });
                    }
                }
            } else if self.engine.active_position().is_some() {
                // A new position opened
                if let (Some(pos), Some(intent)) =
                    (self.engine.active_position(), self.engine.active_intent())
                {
                    events.push(PaperTradingEvent::SignalGenerated(intent.clone()));
                    events.push(PaperTradingEvent::PositionOpened {
                        side: pos.side,
                        entry_price: pos.entry_price,
                        quantity: pos.quantity,
                        stop_loss: intent.stop_loss,
                        take_profit: intent.take_profit,
                    });
                }
            }
        }

        // 3. Broadcast events to all active subscribers
        for event in &events {
            let _ = self.event_sender.send(event.clone());
        }

        events
    }

    /// Terminates the paper trading session, liquidating any open position at the mark price,
    /// and compiling statistical metrics and trade history.
    pub fn finish(self, last_mark_price: Option<Decimal>) -> (BacktestMetrics, Vec<ClosedTrade>) {
        self.engine.finish_with_trades(last_mark_price)
    }

    /// Access the underlying backtest engine simulator.
    #[inline]
    pub fn engine(&self) -> &BacktestEngine {
        &self.engine
    }

    /// Access the underlying dollar bar aggregator.
    #[inline]
    pub fn aggregator(&self) -> &DollarBarAggregator {
        &self.aggregator
    }

    /// Access the underlying strategy.
    #[inline]
    pub fn strategy(&self) -> &DollarBarsCusumStrategy {
        &self.strategy
    }

    /// Current portfolio cash equity balance.
    #[inline]
    pub fn cash_equity(&self) -> Decimal {
        self.engine.cash_equity()
    }

    /// Total portfolio equity mark-to-market.
    #[inline]
    pub fn total_equity(&self, current_price: Decimal) -> Decimal {
        self.engine.total_equity(current_price)
    }

    /// Currently active simulated position, if any.
    #[inline]
    pub fn active_position(&self) -> Option<&Position> {
        self.engine.active_position()
    }

    /// Active order intent, if any.
    #[inline]
    pub fn active_intent(&self) -> Option<&domain::OrderIntent> {
        self.engine.active_intent()
    }

    /// Slice of all closed trades recorded so far.
    #[inline]
    pub fn closed_trades(&self) -> &[ClosedTrade] {
        self.engine.closed_trades()
    }

    /// Bars held for the active position.
    #[inline]
    pub fn bars_held(&self) -> usize {
        self.engine.bars_held()
    }

    /// Peak equity reached during the session.
    #[inline]
    pub fn peak_equity(&self) -> Decimal {
        self.engine.peak_equity()
    }

    /// Maximum drawdown amount observed.
    #[inline]
    pub fn max_drawdown_amount(&self) -> Decimal {
        self.engine.max_drawdown_amount()
    }

    /// Maximum drawdown percentage observed.
    #[inline]
    pub fn max_drawdown_pct(&self) -> Decimal {
        self.engine.max_drawdown_pct()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use domain::Side;
    use rust_decimal_macros::dec;

    fn make_trade(timestamp: i64, price: Decimal, quantity: Decimal, side: Side) -> Trade {
        Trade::new(timestamp, price, quantity, side).expect("valid trade")
    }

    #[test]
    fn test_paper_session_initialization() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(1000),
            ..Default::default()
        };
        let session = PaperTradingSession::new(config).expect("init session");
        assert_eq!(session.cash_equity(), dec!(10_000));
        assert!(session.active_position().is_none());
        assert_eq!(session.closed_trades().len(), 0);
    }

    #[test]
    fn test_trade_processing_and_bar_formation() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(1000),
            ..Default::default()
        };
        let mut session = PaperTradingSession::new(config).expect("init session");
        let mut rx = session.subscribe();

        // Trade 1: $100 * 5 = $500 (threshold 1000 not met)
        let t1 = make_trade(1000, dec!(100), dec!(5), Side::Buy);
        let events1 = session.process_trade(&t1);
        assert!(events1.is_empty());
        assert!(rx.try_recv().is_err());

        // Trade 2: $100 * 6 = $600 -> Total $1100 >= $1000 -> Bar completes!
        let t2 = make_trade(2000, dec!(100), dec!(6), Side::Buy);
        let events2 = session.process_trade(&t2);
        assert!(!events2.is_empty());

        match &events2[0] {
            PaperTradingEvent::BarFormed(bar) => {
                assert_eq!(bar.open, dec!(100));
                assert_eq!(bar.close, dec!(100));
                assert_eq!(bar.volume, dec!(11));
                assert_eq!(bar.dollar_volume, dec!(1100));
                assert_eq!(bar.trade_count, 2);
            }
            _ => panic!("Expected BarFormed event"),
        }

        // Verify broadcast receiver got the same event
        let broadcasted = rx.try_recv().expect("broadcast event");
        assert_eq!(broadcasted, events2[0]);
    }

    #[test]
    fn test_lifecycle_entry_mark_to_market_and_exit() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100), // Small threshold for quick bar creation
            backtest: BacktestConfig {
                initial_capital: dec!(10000),
                maker_fee_pct: dec!(0.0002),
                taker_fee_pct: dec!(0.0005),
                slippage_pct: dec!(0.0005),
                risk_per_trade_pct: dec!(0.01),
                max_daily_drawdown_pct: dec!(0.05),
            },
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(3.0),
                time_barrier_bars: 10,
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");
        let mut rx = session.subscribe();

        // 1. Establish baseline volatility with 4 bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            let trade = make_trade(ts, *p, dec!(1.0), Side::Buy); // $100 notional completes bar
            let events = session.process_trade(&trade);
            assert!(events
                .iter()
                .any(|e| matches!(e, PaperTradingEvent::BarFormed(_))));
        }

        assert!(session.active_position().is_none());

        // 2. Sharp price drop to 90 -> creates bar, triggers Long entry!
        let plunge_trade = make_trade(5000, dec!(90), dec!(1.5), Side::Sell);
        let plunge_events = session.process_trade(&plunge_trade);

        assert!(session.active_position().is_some());
        let pos = session.active_position().unwrap();
        assert_eq!(pos.side, PositionSide::Long);

        // Verify SignalGenerated and PositionOpened events were emitted
        assert!(plunge_events
            .iter()
            .any(|e| matches!(e, PaperTradingEvent::SignalGenerated(_))));
        assert!(plunge_events
            .iter()
            .any(|e| matches!(e, PaperTradingEvent::PositionOpened { .. })));

        // Drain broadcast receiver
        while rx.try_recv().is_ok() {}

        // 3. Next tick: test MarkToMarket generation with active position
        let tick = make_trade(5500, dec!(91), dec!(0.1), Side::Buy);
        let tick_events = session.process_trade(&tick);
        assert_eq!(tick_events.len(), 1);
        match &tick_events[0] {
            PaperTradingEvent::MarkToMarket {
                current_price,
                unrealized_pnl,
                total_equity,
                ..
            } => {
                assert_eq!(*current_price, dec!(91));
                assert!(*unrealized_pnl > Decimal::ZERO); // bought near ~90, price is 91
                assert!(*total_equity > Decimal::ZERO);
            }
            _ => panic!("Expected MarkToMarket event"),
        }

        // 4. Rebound back above mean (100) -> completes bar, triggers TakeProfit!
        let exit_trade = make_trade(6000, dec!(101), dec!(1.0), Side::Buy);
        let exit_events = session.process_trade(&exit_trade);

        assert!(session.active_position().is_none());
        let pos_closed = exit_events
            .iter()
            .find(|e| matches!(e, PaperTradingEvent::PositionClosed { .. }));
        assert!(pos_closed.is_some());

        if let Some(PaperTradingEvent::PositionClosed {
            exit_reason,
            net_pnl,
            ..
        }) = pos_closed
        {
            assert_eq!(exit_reason, "TakeProfit");
            assert!(*net_pnl > Decimal::ZERO);
        }

        // 5. Finish session
        let (metrics, trades) = session.finish(None);
        assert_eq!(metrics.total_trades, 1);
        assert_eq!(metrics.winning_trades, 1);
        assert_eq!(trades.len(), 1);
    }

    #[test]
    fn test_stop_loss_exit_event() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(2.0),
                time_barrier_bars: 10,
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");

        // Baseline bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            session.process_trade(&make_trade(ts, *p, dec!(1.0), Side::Buy));
        }

        // Long entry on dip
        session.process_trade(&make_trade(5000, dec!(90), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_some());

        // Price crashes further to 70 -> Stop Loss
        let crash_events =
            session.process_trade(&make_trade(6000, dec!(70), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_none());

        let closed = crash_events
            .iter()
            .find(|e| matches!(e, PaperTradingEvent::PositionClosed { .. }))
            .expect("PositionClosed event");

        if let PaperTradingEvent::PositionClosed {
            exit_reason,
            net_pnl,
            ..
        } = closed
        {
            assert_eq!(exit_reason, "StopLoss");
            assert!(*net_pnl < Decimal::ZERO);
        }
    }

    #[test]
    fn test_time_barrier_exit_event() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(5.0), // very wide SL
                time_barrier_bars: 2,        // short time barrier
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");

        // Baseline bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            session.process_trade(&make_trade(ts, *p, dec!(1.0), Side::Buy));
        }

        // Enter Long
        session.process_trade(&make_trade(5000, dec!(90), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_some());

        // Bar 1 of holding: price stays near 90
        session.process_trade(&make_trade(6000, dec!(90.1), dec!(1.2), Side::Buy));
        assert!(session.active_position().is_some());
        assert_eq!(session.bars_held(), 1);

        // Bar 2 of holding: time barrier (max_bars_hold = 2) reached!
        let events = session.process_trade(&make_trade(7000, dec!(90.2), dec!(1.2), Side::Buy));
        assert!(session.active_position().is_none());

        let closed = events
            .iter()
            .find(|e| matches!(e, PaperTradingEvent::PositionClosed { .. }))
            .expect("PositionClosed event");

        if let PaperTradingEvent::PositionClosed { exit_reason, .. } = closed {
            assert_eq!(exit_reason, "TimeBarrier");
        }
    }

    #[test]
    fn test_finish_liquidates_open_position() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(5.0),
                time_barrier_bars: 10,
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");

        // Baseline bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            session.process_trade(&make_trade(ts, *p, dec!(1.0), Side::Buy));
        }

        // Enter Long
        session.process_trade(&make_trade(5000, dec!(90), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_some());

        // Terminate session with mark price of 95
        let (metrics, trades) = session.finish(Some(dec!(95)));
        assert_eq!(metrics.total_trades, 1);
        assert_eq!(trades.len(), 1);
        assert!(trades[0].pnl_net > Decimal::ZERO);
    }
}
