//! Real-time paper trading engine for ATSNT.
//!
//! Provides live event-driven paper execution matching incoming trade ticks against
//! synthetic dollar bar aggregations, executing signals via the deterministic [`BacktestEngine`],
//! and broadcasting real-time lifecycle events ([`PaperTradingEvent`]) over Tokio channels.

use domain::{DollarBar, DollarBarAggregator, Position, PositionSide, Trade};
use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use serde::{Deserialize, Serialize};
use strategies::{DollarBarsCusumConfig, DollarBarsCusumStrategy};
use tokio::sync::{broadcast, mpsc};

use crate::config::BacktestConfig;
use crate::engine::BacktestEngine;
use crate::error::BacktestError;
use crate::metrics::{BacktestMetrics, ClosedTrade};

/// Real-time lifecycle events emitted during paper trading execution.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PaperTradingEvent {
    /// A new Dollar Bar has finalized after reaching the sampling dollar threshold.
    BarFormed(DollarBar),
    /// An algorithmic trading signal intent was generated by the active strategy.
    SignalGenerated(domain::OrderIntent),
    /// A simulated market position has opened with friction (slippage + fee drag).
    PositionOpened {
        /// Position side (Long or Short).
        side: PositionSide,
        /// Simulated execution entry price (including slippage).
        entry_price: Decimal,
        /// Executed order size in base asset units.
        quantity: Decimal,
        /// Stop loss barrier price.
        stop_loss: Decimal,
        /// Take profit barrier price.
        take_profit: Decimal,
    },
    /// A simulated market position has closed due to barrier breach or time limit.
    PositionClosed {
        /// Reason for exit: "StopLoss", "TakeProfit", or "TimeBarrier".
        exit_reason: String,
        /// Simulated exit execution price.
        exit_price: Decimal,
        /// Realized net PnL after all fees and slippage.
        net_pnl: Decimal,
        /// Updated portfolio cash equity after trade settlement.
        total_equity: Decimal,
    },
    /// Live mark-to-market valuation against incoming market trade tick.
    MarkToMarket {
        /// Current market price tick.
        current_price: Decimal,
        /// Current unrealized PnL of active position.
        unrealized_pnl: Decimal,
        /// Total portfolio equity including unrealized PnL.
        total_equity: Decimal,
        /// Current peak-to-trough drawdown percentage.
        drawdown_pct: Decimal,
    },
}

impl PaperTradingEvent {
    /// Stable wire identifier, independent of Rust debug formatting.
    pub fn event_type(&self) -> &'static str {
        match self {
            Self::BarFormed(_) => "BarFormed",
            Self::SignalGenerated(_) => "SignalGenerated",
            Self::PositionOpened { .. } => "PositionOpened",
            Self::PositionClosed { .. } => "PositionClosed",
            Self::MarkToMarket { .. } => "MarkToMarket",
        }
    }
}

/// Explicit identity of one telemetry-producing session.
///
/// Separate from [`PaperTradingConfig`] to preserve existing raw-event callers.
/// The caller supplies the actual instrument and strategy/session identifier;
/// neither can be inferred from an anonymous market trade.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TelemetryConfig {
    /// Instrument traded by this session.
    pub symbol: String,
    /// Caller-selected strategy/session identifier.
    pub strategy_id: String,
}

impl TelemetryConfig {
    /// Wraps an event with its originating market tick's Unix millisecond timestamp.
    pub fn envelope(
        &self,
        timestamp: i64,
        event: PaperTradingEvent,
    ) -> TelemetryEnvelope<PaperTradingEvent> {
        TelemetryEnvelope {
            timestamp: Some(timestamp),
            strategy_id: self.strategy_id.clone(),
            symbol: self.symbol.clone(),
            event_type: event.event_type().to_string(),
            payload: event,
        }
    }
}

/// Stable telemetry wire envelope shared by lifecycle events and snapshots.
/// Lifecycle payloads retain the raw enum's existing externally tagged JSON.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TelemetryEnvelope<T> {
    /// Originating market event time in Unix milliseconds. `None` is reserved
    /// for an initial snapshot before any market event has been observed.
    pub timestamp: Option<i64>,
    /// Explicit strategy/session identifier.
    pub strategy_id: String,
    /// Explicit instrument identifier.
    pub symbol: String,
    /// Stable event name, not a Rust debug representation.
    pub event_type: String,
    /// Event-specific data.
    pub payload: T,
}

/// Configuration settings for initializing a [`PaperTradingSession`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PaperTradingConfig {
    /// Information threshold in quote currency (USDT) to aggregate a Dollar Bar.
    pub dollar_bar_threshold: Decimal,
    /// Backtesting friction and account parameters.
    pub backtest: BacktestConfig,
    /// Strategy hyperparameters.
    pub strategy: DollarBarsCusumConfig,
    /// Capacity of the Tokio broadcast event channel. Default: 10,000.
    pub channel_capacity: usize,
}

impl Default for PaperTradingConfig {
    fn default() -> Self {
        Self {
            dollar_bar_threshold: dec!(50_000),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig::default(),
            channel_capacity: 10_000,
        }
    }
}

/// Live event-driven paper trading session coordinator.
///
/// Bridges live incoming market trades with the deterministic [`BacktestEngine`]
/// and [`DollarBarsCusumStrategy`], broadcasting execution telemetry in real time.
pub struct PaperTradingSession {
    aggregator: DollarBarAggregator,
    strategy: DollarBarsCusumStrategy,
    engine: BacktestEngine,
    event_sender: broadcast::Sender<PaperTradingEvent>,
    telemetry: Option<(
        TelemetryConfig,
        broadcast::Sender<TelemetryEnvelope<PaperTradingEvent>>,
    )>,
}

impl PaperTradingSession {
    /// Initializes a new paper trading session from the provided configuration.
    pub fn new(config: PaperTradingConfig) -> Result<Self, BacktestError> {
        let aggregator = DollarBarAggregator::new(config.dollar_bar_threshold)?;
        let strategy = DollarBarsCusumStrategy::new(config.strategy)?;
        let engine = BacktestEngine::new(config.backtest);
        let capacity = if config.channel_capacity == 0 {
            10_000
        } else {
            config.channel_capacity
        };
        let (event_sender, _) = broadcast::channel(capacity);

        Ok(Self {
            aggregator,
            strategy,
            engine,
            event_sender,
            telemetry: None,
        })
    }

    /// Initializes an explicitly identified session with an additional envelope channel.
    /// Raw subscriptions and [`Self::process_trade`] return values are unchanged.
    pub fn new_with_telemetry(
        config: PaperTradingConfig,
        telemetry: TelemetryConfig,
    ) -> Result<Self, BacktestError> {
        let capacity = if config.channel_capacity == 0 {
            10_000
        } else {
            config.channel_capacity
        };
        let mut session = Self::new(config)?;
        let (sender, _) = broadcast::channel(capacity);
        session.telemetry = Some((telemetry, sender));
        Ok(session)
    }

    /// Subscribes to identified envelopes, or returns `None` for raw-only sessions.
    pub fn subscribe_telemetry(
        &self,
    ) -> Option<broadcast::Receiver<TelemetryEnvelope<PaperTradingEvent>>> {
        self.telemetry
            .as_ref()
            .map(|(_, sender)| sender.subscribe())
    }

    /// Initializes a paper trading session with pre-built components.
    pub fn from_components(
        aggregator: DollarBarAggregator,
        strategy: DollarBarsCusumStrategy,
        engine: BacktestEngine,
        channel_capacity: usize,
    ) -> Self {
        let capacity = if channel_capacity == 0 {
            10_000
        } else {
            channel_capacity
        };
        let (event_sender, _) = broadcast::channel(capacity);

        Self {
            aggregator,
            strategy,
            engine,
            event_sender,
            telemetry: None,
        }
    }

    /// Creates a new broadcast receiver to subscribe to live paper trading events.
    pub fn subscribe(&self) -> broadcast::Receiver<PaperTradingEvent> {
        self.event_sender.subscribe()
    }

    /// Access the underlying broadcast sender channel.
    pub fn event_sender(&self) -> broadcast::Sender<PaperTradingEvent> {
        self.event_sender.clone()
    }

    /// Ingests a live market trade, steps the aggregator, evaluates strategy signals
    /// and barrier exits, and returns all events generated during this tick.
    pub fn process_trade(&mut self, trade: &Trade) -> Vec<PaperTradingEvent> {
        let mut events = Vec::new();

        // 1. Mark to market on current trade if there is an active position
        if let Some(pos) = self.engine.active_position() {
            let unrealized_pnl = pos.unrealized_pnl(trade.price);
            let total_equity = self.engine.total_equity(trade.price);
            let peak_equity = self.engine.peak_equity();
            let drawdown_pct = if peak_equity > Decimal::ZERO && peak_equity > total_equity {
                (peak_equity - total_equity) / peak_equity
            } else {
                Decimal::ZERO
            };

            events.push(PaperTradingEvent::MarkToMarket {
                current_price: trade.price,
                unrealized_pnl,
                total_equity,
                drawdown_pct,
            });
        }

        // 2. Ingest trade into the DollarBarAggregator
        if let Some(bar) = self.aggregator.process_trade(trade) {
            events.push(PaperTradingEvent::BarFormed(bar.clone()));

            let had_pos = self.engine.active_position().cloned();
            let had_intent = self.engine.active_intent().cloned();
            let next_bars_held = self.engine.bars_held() + 1;

            self.engine.process_bar(&mut self.strategy, &bar);

            // Check if active position closed
            if let (Some(pos), Some(intent)) = (had_pos, had_intent) {
                if self.engine.active_position().is_none() {
                    let exit_reason = match pos.side {
                        PositionSide::Long => {
                            if bar.low <= intent.stop_loss {
                                "StopLoss"
                            } else if bar.high >= intent.take_profit {
                                "TakeProfit"
                            } else if next_bars_held >= intent.max_bars_hold {
                                "TimeBarrier"
                            } else {
                                "Unknown"
                            }
                        }
                        PositionSide::Short => {
                            if bar.high >= intent.stop_loss {
                                "StopLoss"
                            } else if bar.low <= intent.take_profit {
                                "TakeProfit"
                            } else if next_bars_held >= intent.max_bars_hold {
                                "TimeBarrier"
                            } else {
                                "Unknown"
                            }
                        }
                    };

                    if let Some(closed_trade) = self.engine.closed_trades().last() {
                        let exit_price = if pos.quantity > Decimal::ZERO {
                            match pos.side {
                                PositionSide::Long => {
                                    pos.entry_price + (closed_trade.pnl_gross / pos.quantity)
                                }
                                PositionSide::Short => {
                                    pos.entry_price - (closed_trade.pnl_gross / pos.quantity)
                                }
                            }
                        } else {
                            bar.close
                        };

                        events.push(PaperTradingEvent::PositionClosed {
                            exit_reason: exit_reason.to_string(),
                            exit_price,
                            net_pnl: closed_trade.pnl_net,
                            total_equity: self.engine.cash_equity(),
                        });
                    }
                }
            } else if self.engine.active_position().is_some() {
                // A new position opened
                if let (Some(pos), Some(intent)) =
                    (self.engine.active_position(), self.engine.active_intent())
                {
                    events.push(PaperTradingEvent::SignalGenerated(intent.clone()));
                    events.push(PaperTradingEvent::PositionOpened {
                        side: pos.side,
                        entry_price: pos.entry_price,
                        quantity: pos.quantity,
                        stop_loss: intent.stop_loss,
                        take_profit: intent.take_profit,
                    });
                }
            }
        }

        // 3. Broadcast events to all active subscribers
        for event in &events {
            let _ = self.event_sender.send(event.clone());
            if let Some((metadata, sender)) = &self.telemetry {
                let _ = sender.send(metadata.envelope(trade.timestamp, event.clone()));
            }
        }

        events
    }

    /// Terminates the paper trading session, liquidating any open position at the mark price,
    /// and compiling statistical metrics and trade history.
    pub fn finish(self, last_mark_price: Option<Decimal>) -> (BacktestMetrics, Vec<ClosedTrade>) {
        self.engine.finish_with_trades(last_mark_price)
    }

    /// Access the underlying backtest engine simulator.
    #[inline]
    pub fn engine(&self) -> &BacktestEngine {
        &self.engine
    }

    /// Access the underlying dollar bar aggregator.
    #[inline]
    pub fn aggregator(&self) -> &DollarBarAggregator {
        &self.aggregator
    }

    /// Access the underlying strategy.
    #[inline]
    pub fn strategy(&self) -> &DollarBarsCusumStrategy {
        &self.strategy
    }

    /// Current portfolio cash equity balance.
    #[inline]
    pub fn cash_equity(&self) -> Decimal {
        self.engine.cash_equity()
    }

    /// Total portfolio equity mark-to-market.
    #[inline]
    pub fn total_equity(&self, current_price: Decimal) -> Decimal {
        self.engine.total_equity(current_price)
    }

    /// Currently active simulated position, if any.
    #[inline]
    pub fn active_position(&self) -> Option<&Position> {
        self.engine.active_position()
    }

    /// Active order intent, if any.
    #[inline]
    pub fn active_intent(&self) -> Option<&domain::OrderIntent> {
        self.engine.active_intent()
    }

    /// Slice of all closed trades recorded so far.
    #[inline]
    pub fn closed_trades(&self) -> &[ClosedTrade] {
        self.engine.closed_trades()
    }

    /// Bars held for the active position.
    #[inline]
    pub fn bars_held(&self) -> usize {
        self.engine.bars_held()
    }

    /// Peak equity reached during the session.
    #[inline]
    pub fn peak_equity(&self) -> Decimal {
        self.engine.peak_equity()
    }

    /// Maximum drawdown amount observed.
    #[inline]
    pub fn max_drawdown_amount(&self) -> Decimal {
        self.engine.max_drawdown_amount()
    }

    /// Maximum drawdown percentage observed.
    #[inline]
    pub fn max_drawdown_pct(&self) -> Decimal {
        self.engine.max_drawdown_pct()
    }
}

/// Owns the source-waiting input and task until explicit shutdown.
pub struct PaperSessionRuntime {
    input: mpsc::Sender<Trade>,
    task: tokio::task::JoinHandle<(BacktestMetrics, Vec<ClosedTrade>)>,
}

impl PaperSessionRuntime {
    /// Starts a session without creating a trade producer.
    pub fn spawn(owner: PaperSessionOwner, input: mpsc::Sender<Trade>) -> Self {
        Self {
            input,
            task: tokio::spawn(owner.run()),
        }
    }

    /// Closes the owned input, drains queued trades, and joins finalization.
    /// The input has no external clones in this source-waiting runtime.
    pub async fn shutdown(
        self,
    ) -> Result<(BacktestMetrics, Vec<ClosedTrade>), tokio::task::JoinError> {
        drop(self.input);
        self.task.await
    }
}

/// Owns one paper session and its bounded input receiver.
/// No market-data producer is created by this boundary.
pub struct PaperSessionOwner {
    session: PaperTradingSession,
    trades: mpsc::Receiver<Trade>,
    telemetry: TelemetryConfig,
    events: broadcast::Sender<TelemetryEnvelope<PaperTradingEvent>>,
}

impl PaperSessionOwner {
    /// Creates a session and bounded source handle. Unknown identity stays empty.
    /// The caller must configure identity from its source, never infer it from Trade.
    pub fn new(
        config: PaperTradingConfig,
        telemetry: Option<TelemetryConfig>,
        events: broadcast::Sender<TelemetryEnvelope<PaperTradingEvent>>,
    ) -> Result<(Self, mpsc::Sender<Trade>), BacktestError> {
        let capacity = config.channel_capacity.max(1);
        let session = PaperTradingSession::new(config)?;
        let (input, trades) = mpsc::channel(capacity);
        Ok((
            Self {
                session,
                trades,
                telemetry: telemetry.unwrap_or(TelemetryConfig {
                    symbol: String::new(),
                    strategy_id: String::new(),
                }),
                events,
            },
            input,
        ))
    }

    /// Waits for supplied trades, forwarding session events to the telemetry sender.
    pub async fn run(mut self) -> (BacktestMetrics, Vec<ClosedTrade>) {
        while let Some(trade) = self.trades.recv().await {
            for event in self.session.process_trade(&trade) {
                let _ = self
                    .events
                    .send(self.telemetry.envelope(trade.timestamp, event));
            }
        }
        // Consuming finish guarantees one finalization. No mark means no forced
        // liquidation; finalization itself does not publish a telemetry event.
        self.session.finish(None)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use domain::Side;
    use rust_decimal_macros::dec;

    fn make_trade(timestamp: i64, price: Decimal, quantity: Decimal, side: Side) -> Trade {
        Trade::new(timestamp, price, quantity, side).expect("valid trade")
    }

    #[test]
    fn test_paper_session_initialization() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(1000),
            ..Default::default()
        };
        let session = PaperTradingSession::new(config).expect("init session");
        assert_eq!(session.cash_equity(), dec!(10_000));
        assert!(session.active_position().is_none());
        assert_eq!(session.closed_trades().len(), 0);
    }

    #[test]
    fn test_trade_processing_and_bar_formation() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(1000),
            ..Default::default()
        };
        let mut session = PaperTradingSession::new(config).expect("init session");
        let mut rx = session.subscribe();

        // Trade 1: $100 * 5 = $500 (threshold 1000 not met)
        let t1 = make_trade(1000, dec!(100), dec!(5), Side::Buy);
        let events1 = session.process_trade(&t1);
        assert!(events1.is_empty());
        assert!(rx.try_recv().is_err());

        // Trade 2: $100 * 6 = $600 -> Total $1100 >= $1000 -> Bar completes!
        let t2 = make_trade(2000, dec!(100), dec!(6), Side::Buy);
        let events2 = session.process_trade(&t2);
        assert!(!events2.is_empty());

        match &events2[0] {
            PaperTradingEvent::BarFormed(bar) => {
                assert_eq!(bar.open, dec!(100));
                assert_eq!(bar.close, dec!(100));
                assert_eq!(bar.volume, dec!(11));
                assert_eq!(bar.dollar_volume, dec!(1100));
                assert_eq!(bar.trade_count, 2);
            }
            _ => panic!("Expected BarFormed event"),
        }

        // Verify broadcast receiver got the same event
        let broadcasted = rx.try_recv().expect("broadcast event");
        assert_eq!(broadcasted, events2[0]);
    }

    #[test]
    fn test_lifecycle_entry_mark_to_market_and_exit() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100), // Small threshold for quick bar creation
            backtest: BacktestConfig {
                initial_capital: dec!(10000),
                maker_fee_pct: dec!(0.0002),
                taker_fee_pct: dec!(0.0005),
                slippage_pct: dec!(0.0005),
                risk_per_trade_pct: dec!(0.01),
                max_daily_drawdown_pct: dec!(0.05),
            },
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(3.0),
                time_barrier_bars: 10,
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");
        let mut rx = session.subscribe();

        // 1. Establish baseline volatility with 4 bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            let trade = make_trade(ts, *p, dec!(1.0), Side::Buy); // $100 notional completes bar
            let events = session.process_trade(&trade);
            assert!(events
                .iter()
                .any(|e| matches!(e, PaperTradingEvent::BarFormed(_))));
        }

        assert!(session.active_position().is_none());

        // 2. Sharp price drop to 90 -> creates bar, triggers Long entry!
        let plunge_trade = make_trade(5000, dec!(90), dec!(1.5), Side::Sell);
        let plunge_events = session.process_trade(&plunge_trade);

        assert!(session.active_position().is_some());
        let pos = session.active_position().unwrap();
        assert_eq!(pos.side, PositionSide::Long);

        // Verify SignalGenerated and PositionOpened events were emitted
        assert!(plunge_events
            .iter()
            .any(|e| matches!(e, PaperTradingEvent::SignalGenerated(_))));
        assert!(plunge_events
            .iter()
            .any(|e| matches!(e, PaperTradingEvent::PositionOpened { .. })));

        // Drain broadcast receiver
        while rx.try_recv().is_ok() {}

        // 3. Next tick: test MarkToMarket generation with active position
        let tick = make_trade(5500, dec!(91), dec!(0.1), Side::Buy);
        let tick_events = session.process_trade(&tick);
        assert_eq!(tick_events.len(), 1);
        match &tick_events[0] {
            PaperTradingEvent::MarkToMarket {
                current_price,
                unrealized_pnl,
                total_equity,
                ..
            } => {
                assert_eq!(*current_price, dec!(91));
                assert!(*unrealized_pnl > Decimal::ZERO); // bought near ~90, price is 91
                assert!(*total_equity > Decimal::ZERO);
            }
            _ => panic!("Expected MarkToMarket event"),
        }

        // 4. Rebound back above mean (100) -> completes bar, triggers TakeProfit!
        let exit_trade = make_trade(6000, dec!(101), dec!(1.0), Side::Buy);
        let exit_events = session.process_trade(&exit_trade);

        assert!(session.active_position().is_none());
        let pos_closed = exit_events
            .iter()
            .find(|e| matches!(e, PaperTradingEvent::PositionClosed { .. }));
        assert!(pos_closed.is_some());

        if let Some(PaperTradingEvent::PositionClosed {
            exit_reason,
            net_pnl,
            ..
        }) = pos_closed
        {
            assert_eq!(exit_reason, "TakeProfit");
            assert!(*net_pnl > Decimal::ZERO);
        }

        // 5. Finish session
        let (metrics, trades) = session.finish(None);
        assert_eq!(metrics.total_trades, 1);
        assert_eq!(metrics.winning_trades, 1);
        assert_eq!(trades.len(), 1);
    }

    #[test]
    fn test_stop_loss_exit_event() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(2.0),
                time_barrier_bars: 10,
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");

        // Baseline bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            session.process_trade(&make_trade(ts, *p, dec!(1.0), Side::Buy));
        }

        // Long entry on dip
        session.process_trade(&make_trade(5000, dec!(90), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_some());

        // Price crashes further to 70 -> Stop Loss
        let crash_events =
            session.process_trade(&make_trade(6000, dec!(70), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_none());

        let closed = crash_events
            .iter()
            .find(|e| matches!(e, PaperTradingEvent::PositionClosed { .. }))
            .expect("PositionClosed event");

        if let PaperTradingEvent::PositionClosed {
            exit_reason,
            net_pnl,
            ..
        } = closed
        {
            assert_eq!(exit_reason, "StopLoss");
            assert!(*net_pnl < Decimal::ZERO);
        }
    }

    #[test]
    fn test_time_barrier_exit_event() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(5.0), // very wide SL
                time_barrier_bars: 2,        // short time barrier
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");

        // Baseline bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            session.process_trade(&make_trade(ts, *p, dec!(1.0), Side::Buy));
        }

        // Enter Long
        session.process_trade(&make_trade(5000, dec!(90), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_some());

        // Bar 1 of holding: price stays near 90
        session.process_trade(&make_trade(6000, dec!(90.1), dec!(1.2), Side::Buy));
        assert!(session.active_position().is_some());
        assert_eq!(session.bars_held(), 1);

        // Bar 2 of holding: time barrier (max_bars_hold = 2) reached!
        let events = session.process_trade(&make_trade(7000, dec!(90.2), dec!(1.2), Side::Buy));
        assert!(session.active_position().is_none());

        let closed = events
            .iter()
            .find(|e| matches!(e, PaperTradingEvent::PositionClosed { .. }))
            .expect("PositionClosed event");

        if let PaperTradingEvent::PositionClosed { exit_reason, .. } = closed {
            assert_eq!(exit_reason, "TimeBarrier");
        }
    }

    #[test]
    fn test_finish_liquidates_open_position() {
        let config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100),
            backtest: BacktestConfig::default(),
            strategy: DollarBarsCusumConfig {
                rolling_window_len: 4,
                cusum_vol_multiplier: dec!(1.0),
                z_entry_threshold: dec!(1.5),
                z_stop_threshold: dec!(5.0),
                time_barrier_bars: 10,
            },
            channel_capacity: 100,
        };

        let mut session = PaperTradingSession::new(config).expect("init session");

        // Baseline bars
        for (i, p) in [dec!(100), dec!(101), dec!(99), dec!(100)]
            .iter()
            .enumerate()
        {
            let ts = (i as i64 + 1) * 1000;
            session.process_trade(&make_trade(ts, *p, dec!(1.0), Side::Buy));
        }

        // Enter Long
        session.process_trade(&make_trade(5000, dec!(90), dec!(1.5), Side::Sell));
        assert!(session.active_position().is_some());

        // Terminate session with mark price of 95
        let (metrics, trades) = session.finish(Some(dec!(95)));
        assert_eq!(metrics.total_trades, 1);
        assert_eq!(trades.len(), 1);
        assert!(trades[0].pnl_net > Decimal::ZERO);
    }

    #[tokio::test]
    async fn shutdown_drains_input_joins_and_returns_finalized_metrics() {
        use tokio::time::{timeout, Duration};
        let (events, _) = broadcast::channel(16);
        let mut rx = events.subscribe();
        let (owner, input) = PaperSessionOwner::new(
            PaperTradingConfig {
                dollar_bar_threshold: dec!(1000),
                channel_capacity: 2,
                ..Default::default()
            },
            None,
            events,
        )
        .unwrap();
        // Queue before spawning: shutdown must drain, not abort the task.
        input
            .try_send(Trade::new(42, dec!(100), dec!(11), Side::Buy).unwrap())
            .unwrap();
        let runtime = PaperSessionRuntime::spawn(owner, input);
        let (metrics, trades) = timeout(Duration::from_secs(1), runtime.shutdown())
            .await
            .unwrap()
            .unwrap();
        assert_eq!(metrics.total_trades, 0);
        assert!(trades.is_empty());
        let event = rx.try_recv().unwrap();
        assert_eq!(event.timestamp, Some(42));
        assert!(matches!(event.payload, PaperTradingEvent::BarFormed(_)));
        assert!(matches!(
            rx.try_recv(),
            Err(broadcast::error::TryRecvError::Closed)
        ));
    }

    #[tokio::test]
    async fn shutdown_does_not_liquidate_an_open_position_or_emit_a_final_event() {
        use tokio::time::{timeout, Duration};
        let (events, _) = broadcast::channel(16);
        let mut rx = events.subscribe();
        let mut config = PaperTradingConfig {
            dollar_bar_threshold: dec!(100),
            ..Default::default()
        };
        config.strategy.rolling_window_len = 4;
        config.strategy.cusum_vol_multiplier = dec!(1);
        config.strategy.z_entry_threshold = dec!(1.5);
        config.strategy.z_stop_threshold = dec!(3);
        config.strategy.time_barrier_bars = 10;
        let (mut owner, input) = PaperSessionOwner::new(config, None, events).unwrap();
        for (i, price) in [dec!(100), dec!(101), dec!(99), dec!(100), dec!(90)]
            .into_iter()
            .enumerate()
        {
            owner.session.process_trade(
                &Trade::new((i as i64 + 1) * 1000, price, dec!(1.5), Side::Buy).unwrap(),
            );
        }
        assert!(owner.session.active_position().is_some());
        let runtime = PaperSessionRuntime::spawn(owner, input);
        let (metrics, trades) = timeout(Duration::from_secs(1), runtime.shutdown())
            .await
            .unwrap()
            .unwrap();
        assert_eq!(metrics.total_trades, 0);
        assert!(trades.is_empty());
        assert!(matches!(
            rx.try_recv(),
            Err(broadcast::error::TryRecvError::Closed)
        ));
    }

    #[tokio::test]
    async fn shutdown_joins_a_session_waiting_without_a_source() {
        use tokio::time::{timeout, Duration};
        let (events, _) = broadcast::channel(16);
        let mut rx = events.subscribe();
        let (owner, input) =
            PaperSessionOwner::new(PaperTradingConfig::default(), None, events).unwrap();
        let runtime = PaperSessionRuntime::spawn(owner, input);
        let (metrics, trades) = timeout(Duration::from_secs(1), runtime.shutdown())
            .await
            .unwrap()
            .unwrap();
        assert_eq!(metrics.total_trades, 0);
        assert!(trades.is_empty());
        assert!(matches!(
            rx.try_recv(),
            Err(broadcast::error::TryRecvError::Closed)
        ));
    }

    #[tokio::test]
    async fn input_is_bounded_and_unknown_identity_is_not_invented() {
        let (events, _) = broadcast::channel(16);
        let mut rx = events.subscribe();
        let (owner, input) = PaperSessionOwner::new(
            PaperTradingConfig {
                dollar_bar_threshold: dec!(1000),
                channel_capacity: 1,
                ..Default::default()
            },
            None,
            events,
        )
        .unwrap();
        let trade = Trade::new(42, dec!(100), dec!(5), Side::Buy).unwrap();
        input.try_send(trade.clone()).unwrap();
        assert!(matches!(
            input.try_send(trade.clone()),
            Err(mpsc::error::TrySendError::Full(_))
        ));
        let task = tokio::spawn(owner.run());
        input.send(trade).await.unwrap();
        drop(input);
        task.await.unwrap();
        let event = rx.try_recv().unwrap();
        assert_eq!(event.timestamp, Some(42));
        assert!(event.symbol.is_empty());
        assert!(event.strategy_id.is_empty());
        assert!(rx.try_recv().is_err());
    }
}
